name: edk2 build
on: [push,workflow_dispatch]

jobs:
  build:
    name: Build ${{ matrix.platform }}
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        include:
          - runner: ubicloud-standard-2
            platform: x64
          - runner: ubicloud-standard-2-arm
            platform: arm64

    steps:
      - name: Code checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get -y install uuid-dev iasl build-essential python3-distutils git libbrotli-dev nasm
      - name: Build edk2
        run: ./build-edk2
      - name: List produced files
        run: ls
      - uses: ncipollo/release-action@v1
        if: github.event_name == 'workflow_dispatch' && github.ref_type == 'tag'
        with:
          artifacts: "${{ github.workspace }}/CLOUDHV-${{ matrix.platform }}.fd"
          body: "Release ${{ github.ref_name }}"
          allowUpdates: true
